# Generated by Django 4.2.2 on 2023-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='quantidade_views',
        ),
        migrations.AddField(
            model_name='filme',
            name='numero_views',
            field=models.IntegerField(default=0),
        ),
    ]
