# Generated by Django 4.2.2 on 2023-06-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_remove_filme_quantidade_views_filme_numero_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='numero_views',
        ),
        migrations.AddField(
            model_name='filme',
            name='classificao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filme',
            name='quantidade_views',
            field=models.IntegerField(default=0),
        ),
    ]
